### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by longnd** [21jake/nimble-scraper#34]
Hello Thang👋 
Thank you for your effort on the code submission. I am Long, engineering lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by longnd** [comment]
I have completed the first round of reviews. Please provide your feedback on all open issues :)

**Comment by 21jake** [comment]
Hello @longnd. Appreciate your presence here. I'll try to be as much as available as possible during the review process. Cheers!

**Comment by longnd** [comment]
Thank you for the feedback on all open issues and the fixes done so far.

As explained earlier, we aim to keep the code review process within 2-3 days, so let's end this phase now. There is now sufficient information for us to finalize this technical assessment stage. So the code review is now completed 🙂 

We appreciate your efforts on this code challenge 🙏 Our team will reach out to you in the coming days by email.

**Comment by 21jake** [comment]
I appreciate your time and efforts put into this, and will be looking forward to it.
